name: Build oneDNN libs
on: [push]
jobs:
  Build-for-jammy:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    strategy:
      fail-fast: false
    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install build-essential curl wget git cmake -y
          sudo apt install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu -y
          wget https://github.com/oneapi-src/oneDNN/archive/refs/tags/v3.5.3.tar.gz
          tar -zxvf ./v3.5.3.tar.gz
          cd oneDNN-*
      - name: Build for x86_64
        run: |
          ls
          cd oneDNN-*
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_SYSTEM_NAME=Linux
          make -j40
          mkdir install
          cmake --build . --target install
          cd install
          ls
        continue-on-error: true


          
